### PR TITLE
corrected headers for Jekyll 3.0, added link code

### PR DESCRIPTION
**Pull request by mjones01**

### CODE REVIEW

**Comment by mjones01** [comment]
29 Feb: new commit with a brief style guide for text and code comments based on Zach's suggestions.  Wondering if we should move this example post into the Lesson Building (and data-lessons ?) repo so that it can easily be viewed by collaborators?

**Comment by lwasser** [comment]
Thanks @mjones01 this looks great. a few questions

1. can you add a section to the top that covers style rules? SO 80 characters, function() etc etc? I may be reviewing too quickly so if it's there already - just move it to the top.

2. can we remove some of the older files from this - for instance all of the science video pages, etc. I'm thinking we can keep this repo very simple for the time being. We may eventually move this page to our dev / live site down the road as well - 

Let me know what you think about removing files from this site that we don't need here. then let's start an issue about potentially just integrating this page into our main site. (one less repo to deal with) :)

**Comment by mjones01** [comment]
1) The very top parallels the lessons (YAML & grey box).  The style guide is the first bit that isn't those (e.g., the start of the lesson). 

2) Confirming: Remove the following directories:
boulder-flood
data-workshops
science-videos
test-workshop-lesson-set

I'm in favor of these removals as I don't fully understand why they are there to start with!

**Comment by lwasser** [comment]
Please remove those directories.

**Comment by mjones01** [comment]
Directory cleaned up.  Example post ready for merge (code fixed, will build). 

Long-term: I think we should move these two posts to the Lesson-Building repo. Minor template changes we can test in Lesson-Building before going to Dev.   If we ever want to do major redesigns or test major template changes, we fork NEON-Data-Skills-Dev and create a temporary redesign repo.  

Minimizing the number of repos we need to update and keep track of would be WONDERFUL!

**Comment by lwasser** [comment]
cool - how about you create an issue in this repo that we should move it to lesson building. OR, if you want - go ahead and move it today and we can deprecate this repo altogether? I'm really getting lost with all of these repos! one less is music to my ears :)

**Comment by mjones01** [comment]
Done.  Commit 5d8d3ad in the Lessons Building Repo (pending PR).  Once that PR is accepted and fine, this repo is ready to be deleted.  (I checked the images folder and all were transferred where need).

**Pull request merged**
